export const IMAGES = {
    logo: require ("../assets/images/spotify-logo.png"),
    premiumActive: require ("../assets/images/spotify_splash.png"),
    premiumInactive: require ("../assets/images/spotify-logo.png"),
    phone: require ("../assets/images/phone.png"),
    googleicon: require("../assets/images/Google.png"),
    facebookicon: require ("../assets/images/Facebook.png"),
    homeActive: require ("../assets/images/home (selected).png"),
    homeInactive: require ("../assets/images/home (unselected).png"),
    searchActive: require ("../assets/images/search (selected).png"),
    searchInactive: require ("../assets/images/search (unselected).png"),
    libraryActive: require ("../assets/images/library (unselected).png"),
    libraryInactive: require ("../assets/images/library (unselected).png"),
    justHits: require ("../assets/images/justHits.png"),
    onRepeat:require ("../assets/images/onRepeat.png"),
    baddie:require ("../assets/images/baddie.png"),
    christmas:require ("../assets/images/christmas.png"),
    dailymix:require ("../assets/images/dailymix.png"),
    ariana:require ("../assets/images/ariana.png"),
    missedHits:require ("../assets/images/missedHits.png"),
    kpop:require ("../assets/images/kpop.png"),
    kpopbanner:require ("../assets/images/kpopbanner.png"),
    cozy:require ("../assets/images/cozy.png"),
    korean:require ("../assets/images/korean.png"),
    healing:require ("../assets/images/healing.png"), 
    add:require ("../assets/images/add.png"), 
    play:require ("../assets/images/play.png"), 
    defaultAvatar:require ("../assets/images/defaultAvatar.png"), 
    doja:require ("../assets/images/doja.png"),
    tv:require ("../assets/images/connect to tv_.png"),
    more:require ("../assets/images/more.png"),
    trending1:require ("../assets/images/TFY1.png"),
    trending2:require ("../assets/images/TFY2.png"),
    trending3:require ("../assets/images/TFY3.png"),
};